# Generated by Django 3.2.8 on 2021-10-23 09:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='iamge',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
